### ISSUE TITLE
How to deal with regeneration?

### ISSUE THREAD

**Issue by sefasenturk95** [koxudaxi/fastapi-code-generator#394]
Hi! First of all thank you for this generator, seems a lot more easier to use than the openapi-generator. I was wondering how you deal with regeneration when your spec changes? Do you have a working example of how this generator is used in the real world? Thanks!

**Comment by yyamano** [comment]
I use custom template and visitor to implement delegate pattern.
So the generated code looks as below:

```
@app.post(
    '/upload',
    response_model=bytes,
    responses={'400': {'model': ProblemDetails}, '500': {'model': ProblemDetails}},
)
def upload(
    file: UploadFile,
) -> Union[bytes, ProblemDetails]:
    return upload_service.upload(file)
```

Actual implementation is foo_service.upload(). It is never overwritten.

Hope it might help.

**Comment by sefasenturk95** [comment]
@koxudaxi Thank you very much for your response! This really helps! The thing is now that I have the `generate-router` flag set to true, so I would expect multiple abstract classes in the `abstract.py`, but I don't see a forl oop in the `templates/abstract.jinja2` file so in the meanwhile I try to add it and see if I can work it out.

**Comment by koxudaxi** [comment]
I always generate the abstraction class in this way to separate the generated code from the actual file to be edited.
This is a lovely personal use of the code generator, and it would be nice to have this template available from the CLI options as a preset.
This would have been an excellent option to have existed since the initial release.
How do people manage their auto-generated code? :thinking:

**Comment by koxudaxi** [comment]
@sefasenturk95 
You can apply the same method to routers.
Creating a new custom template is advisable instead of using　`templates/main.jinja2`.
You can reference and copy it from  [modular_template/routers.jinja2](https://github.com/koxudaxi/fastapi-code-generator/blob/master/fastapi_code_generator/modular_template/routers.jinja2).
