### ISSUE TITLE
Please move black to dev-dependencies

### ISSUE THREAD

**Issue by bodograumann** [koxudaxi/fastapi-code-generator#60]
You are listing black as a runtime dependency with a fixed version of 19.1b0. Unfortunately that conflicts with the version I want to use 20.8b1.

Afaics black is only used as a development dependency in this project, so it should be marked as such and the conflict would be resolved.

**Comment by koxudaxi** [comment]
@bodograumann 
I'm sorry. I lost a notification for this issue.
I want your problem. But, black is fixed in `datamodel-code-generator`
`    black>=19.10b0,<20`
https://github.com/koxudaxi/datamodel-code-generator/blob/4e4848fb9f03989599b2c8cc957dc30b4496afa3/setup.cfg#L37

We have to change the version of the cap.
Also, I don't know 20.8b1 is compatible with 19.1b0 🤔

**Comment by bodograumann** [comment]
I see.
Maybe you could make the code formatting in datamodels-code-generator optional, if the user wants to do their own code-formatting.
Then you could also define black as an optional dependency there.

Apart from that I think you still need to move it to dev-dependencies in fastapi-code-generator.

**Comment by koxudaxi** [comment]
@bodograumann 
I moved black to dev-dependencies
https://github.com/koxudaxi/fastapi-code-generator/pull/65/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

And, I released it as `0.0.19`

**Comment by bodograumann** [comment]
Thank you, this works nicely.
